//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQBAL_SORATHIA_INSURANCE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class endousment
    {
        public int id { get; set; }
        public string date { get; set; }
        public string endousment1 { get; set; }
        public string policy { get; set; }
        public string nameofinsured { get; set; }
        public string suminsured { get; set; }
        public string dateofexpiry { get; set; }
        public string addgross { get; set; }
        public string addnet { get; set; }
        public string lessgross { get; set; }
        public string lessnet { get; set; }
        public string receipt { get; set; }
        public string detail { get; set; }
        public string remarks { get; set; }
    }
}
