//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQBAL_SORATHIA_INSURANCE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class adinsuranceEntities1 : DbContext
    {
        public adinsuranceEntities1()
            : base("name=adinsuranceEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<endousment> endousments { get; set; }
        public virtual DbSet<marinecover> marinecovers { get; set; }
        public virtual DbSet<policy> policies { get; set; }
        public virtual DbSet<receipt> receipts { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<type> types { get; set; }
    }
}
