//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQBAL_SORATHIA_INSURANCE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class marinecover
    {
        public int id { get; set; }
        public string date { get; set; }
        public string cno { get; set; }
        public string nameofbank { get; set; }
        public string nameofinsured { get; set; }
        public string foreignvalues { get; set; }
        public string pakrs { get; set; }
        public string item { get; set; }
        public string slipmentfrom { get; set; }
        public string remarks { get; set; }
        public string equivalentvalue { get; set; }
    }
}
