//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQBAL_SORATHIA_INSURANCE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class policy
    {
        public int id { get; set; }
        public string date { get; set; }
        public string policy1 { get; set; }
        public string nameofinsured { get; set; }
        public string suminsuredvalue { get; set; }
        public string grosspremium { get; set; }
        public string netpremium { get; set; }
        public string receipt { get; set; }
        public string endousement { get; set; }
        public string remarks { get; set; }
        public string dateofexpiry { get; set; }
        public Nullable<int> type { get; set; }
        public string cno { get; set; }
        public string risk { get; set; }
        public string nameofvessel { get; set; }
        public string detail { get; set; }
        public string @class { get; set; }
        public string vehicledetail { get; set; }
    }
}
