//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQBAL_SORATHIA_INSURANCE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class receipt
    {
        public int id { get; set; }
        public string date { get; set; }
        public string receipt1 { get; set; }
        public string policy { get; set; }
        public string nameofinsured { get; set; }
        public string marine { get; set; }
        public string fire { get; set; }
        public string engineering { get; set; }
        public string motor { get; set; }
        public string miscilinious { get; set; }
        public string hull { get; set; }
        public string health { get; set; }
        public string remainingnet { get; set; }
    }
}
